### ISSUE TITLE
different result

### ISSUE THREAD

**Issue by siusoon** [gsurma/text_predictor#3]
more a question than an issue: I have tried with the same settings and same input source, but the outcome are different in terms of the output text for each iteration. Is it because you have set the random seed at the beginning or because of the self probability initialization? Many thanks for this and your article, is it great to prompt questions for thinking about the ML processes.

**Comment by gsurma** [comment]
You are correct. Without setting same random seeds our results are expected to be different.

**Comment by siusoon** [comment]
is this the line? 
sample = int(np.searchsorted(total_sum, np.random.rand(1) * sum))

**Comment by gsurma** [comment]
yes and probably something like this for tensorflow `tf.random.set_random_seed(seed)`

**Comment by siusoon** [comment]
thanks!!
